name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    needs: [build, build-darwin-arm64]
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nomi-cli-windows-amd64
          path: artifacts/windows-amd64

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nomi-cli-windows-386
          path: artifacts/windows-386

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nomi-cli-linux-amd64
          path: artifacts/linux-amd64

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nomi-cli-linux-386
          path: artifacts/linux-386

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nomi-cli-linux-arm64
          path: artifacts/linux-arm64

      - name: Download Darwin ARM64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: nomi-cli-darwin-arm64
          path: artifacts/darwin-arm64

      - name: Generate Release Notes
        id: notes
        run: |
          echo "## Release Notes" > release_notes.md
          git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:'- %s' >> release_notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/windows-amd64/nomi-cli.zip
            artifacts/windows-386/nomi-cli.zip
            artifacts/linux-amd64/nomi-cli
            artifacts/linux-386/nomi-cli
            artifacts/linux-arm64/nomi-cli
            artifacts/darwin-arm64/nomi-cli
          body_path: release_notes.md
          token: ${{ secrets.GITHUB_TOKEN }}
